/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.views;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;



/**
 *
 * @author Eder
 */
public class TelaPrincipal extends javax.swing.JFrame {

     private TelaUsuario telaUsuario;   // Declaração da variável telaUsuario
    TelaClientes telaCliente;   // Declaração da variável telaCliente
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        lblUsuarioPrincipal = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        Menu = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        subMenuUsuarios = new javax.swing.JMenuItem();
        cliente = new javax.swing.JMenuItem();
        MenuRel = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        agenda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));

        lblData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblData.setForeground(new java.awt.Color(240, 240, 240));
        lblData.setText("Data");

        lblUsuarioPrincipal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblUsuarioPrincipal.setForeground(new java.awt.Color(240, 240, 240));
        lblUsuarioPrincipal.setText("Usuário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lblUsuarioPrincipal)
                .addGap(170, 170, 170)
                .addComponent(lblData)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioPrincipal)
                    .addComponent(lblData))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 490, 860, 120);

        Desktop.setBackground(new java.awt.Color(255, 255, 255));
        Desktop.setPreferredSize(new java.awt.Dimension(604, 500));

        jPanel2.setBackground(new java.awt.Color(102, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        Desktop.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopLayout.createSequentialGroup()
                .addGap(0, 845, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Desktop);
        Desktop.setBounds(0, 0, 860, 608);

        MenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/register.png"))); // NOI18N
        MenuCadastro.setText("Cadastro");

        subMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/user.png"))); // NOI18N
        subMenuUsuarios.setText("Usuários");
        subMenuUsuarios.setEnabled(false);
        subMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuUsuariosActionPerformed(evt);
            }
        });
        MenuCadastro.add(subMenuUsuarios);

        cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/customer.png"))); // NOI18N
        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        MenuCadastro.add(cliente);

        Menu.add(MenuCadastro);

        MenuRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/report.png"))); // NOI18N
        MenuRel.setText("Relatório");
        MenuRel.setEnabled(false);
        Menu.add(MenuRel);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/help.png"))); // NOI18N
        jMenu3.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        Menu.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/options.png"))); // NOI18N
        jMenu4.setText("Opções");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        Menu.add(jMenu4);

        agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/agenda.png"))); // NOI18N
        agenda.setText("Agenda");
        Menu.add(agenda);

        setJMenuBar(Menu);

        setSize(new java.awt.Dimension(874, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   

    
    private void subMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuUsuariosActionPerformed
     // Abrir a tela de usuários dentro do painel Desktop
    if (telaUsuario == null || !telaUsuario.isVisible()) {  // Verifica se a tela já não foi criada ou se está oculta
        telaUsuario = new TelaUsuario(this); // Passa a referência da TelaPrincipal
        Desktop.add(telaUsuario);
    }

    // Tornar visível a tela de usuários e ocultar a de clientes, se aberta
    telaUsuario.setVisible(true);
    try {
        telaUsuario.setSelected(true); // Focar na tela de usuários
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }

    if (telaCliente != null && telaCliente.isVisible()) {
        telaCliente.setVisible(false); // Ocultar tela de clientes se estiver aberta
    }
    
    }//GEN-LAST:event_subMenuUsuariosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Data atual
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
        
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        //Sair
        int sair = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja sair","Atenção",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(sair);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Chamando a tela Sobre
        TelaSobre tsobre = new TelaSobre();
        tsobre.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        
        // Abrir a tela de clientes dentro do painel Desktop
    if (telaCliente == null || !telaCliente.isVisible()) {  // Verifica se a tela já não foi criada ou se está oculta
        telaCliente = new TelaClientes(this); // Passa a referência da TelaPrincipal
        Desktop.add(telaCliente);
    }

    // Tornar visível a tela de clientes e ocultar a de usuários, se aberta
    telaCliente.setVisible(true);
    try {
        telaCliente.setSelected(true); // Focar na tela de clientes
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }

    if (telaUsuario != null && telaUsuario.isVisible()) {
        telaUsuario.setVisible(false); // Ocultar tela de usuários se estiver aberta
    }

    }//GEN-LAST:event_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar Menu;
    public static javax.swing.JMenu MenuCadastro;
    public static javax.swing.JMenu MenuRel;
    private javax.swing.JMenu agenda;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuarioPrincipal;
    public static javax.swing.JMenuItem subMenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
